// src/components/Tasks.tsx
type Props = {};

const Tasks = (props: Props) => {
  const tasks = [
    {
      category: 'Software',
      title: 'Custom software to run an interactive game show.',
      tags: ['Nextjs', 'MongoDB', 'Socket.io', 'Tailwind', 'Typescript', 'Cypress', 'Express'],
    },
    {
      category: 'E-commerce',
      title: 'Bespoke e-commerce solution for a hardware store.',
      tags: ['NuxtJS', 'Firebase', 'Tailwind', 'ElasticSearch', 'Meilisearch', 'Twilio', 'Mailgun', 'FreightView', 'Payeezy', 'Active Directory'],
    },
    {
      category: 'Webapps',
      title: 'Intuitive dashboard and learning system for a massive tire brand.',
      tags: ['NextJS', 'MongoDB', 'Firebase', 'Tailwind', 'Figma'],
    },
    {
      category: 'Integrations & Tools',
      title: 'Custom integration tool for connecting time-tracking with a payroll system.',
      tags: ['NuxtJS', 'Firebase', 'Quickbooks', 'Toggl', 'Tailwind'],
    },
    {
      category: 'Custom Systems',
      title: 'Multi-tenant, white-label order management system.',
      tags: ['Angular', 'Firebase', 'Material UI', 'Mailgun', 'Typescript'],
    },
    {
      category: 'Custom Systems',
      title: "Redesigned frontend for nationwide hospital's equipment service system.",
      tags: ['Angular', 'Bootstrap', '.NET', 'Typescript', 'Material UI'],
    },
    {
      category: 'Theming',
      title: 'Powerful section-based starter theme template for Drupal and Wordpress.',
      tags: ['PHP', 'Twig', 'Javascript', 'AplineJS', 'Tailwind', 'Wordpress', 'Drupal'],
    },
    {
      category: 'Websites',
      title: 'Dozens of fully custom themes for Drupal and Wordpress.',
      tags: ['PHP', 'Twig', 'AlpineJS', 'Tailwind', 'Drupal', 'WordPress'],
    },
    {
      category: 'Education',
      title: 'Transformed an entire university’s course catalog into dynamic web pages programmatically.',
      tags: ['PHP', 'Twig', 'AlpineJS', 'Tailwind', 'Drupal'],
    },
    {
      category: 'Plugins',
      title: 'Custom plugins to enhance Drupal and Wordpress.',
      tags: ['PHP', 'Javascript', 'Drupal', 'Wordpress'],
    },
  ];

  return (
    <section className='px-4'>
      <div className='dark bg-black rounded-2xl text-white min-h-[80dvh] flex items-center py-[10.25rem]'>
        <div className='container grid gap-10'>
          <p className='text-code'>{'let tasks = {'}</p>

          <div className='grid gap-16'>
            <h2 className='text-heading-1 max-w-[59.375rem] text-balance'>A few favorites I've helped develop and launch.</h2>

            <div className='grid grid-cols-3 gap-x-8 gap-y-16'>
              {tasks.map((task, index) => (
                <div key={index} className='grid gap-5'>
                  <h3 className='text-code-sm uppercase'>{task.category}</h3>
                  <h4 className='text-heading-2'>{task.title}</h4>
                  <p className='text-code-sm uppercase'>{task.tags.join(', ')}</p>
                </div>
              ))}
            </div>
          </div>

          <p className='text-code'>{'}'}</p>
        </div>
      </div>
    </section>
  );
};

export default Tasks;

// components/Tasks.vue
<template>
  <div class="container relative space-y-8">
    <p class="code-block">
      // Tasks I've helped undertake and launch<br />
      
    </p>
    <p class="code-block" aria-hidden="true">
      const tasks =
    </p>

    <ul v-if="sortedTasks" class="grid grid-cols-1 gap-12 sm:grid-cols-2 lg:grid-cols-3">
      <li v-for="task, index in sortedTasks" :key="index" class="text-2xl font-medium dark:text-white">
        <p>{{ task }}</p>
      </li>
      <li class="text-2xl text-soft-white-500 dark:text-gray-700">
        <a href="#contact" class="button button-code">Let's build something awesome together</a>
      </li>
    </ul>

    <p class="code-block">
      tasks.sort("<button @click="changeSort(currentSort)" class="button button-code" type="button" aria-label="Sort tasks">{{ currentSort }}</button>")
    </p>

    <p class="absolute right-0 text-4xl -bottom-10 text-lightula-pink dark:text-darkula-pink">===</p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      currentSort: 'random',
      tasks: [
        "Built a powerful section-based starter theme template for Drupal and Wordpress",
        "Converted a university's entire course catalog into dynamic web pages during daily import",
        "Designed and developed a bespoke e-commerce solution for a hardware store",
        "Developed a custom white-label order management system",
        "Redesigned and built a nationwide hospital's equipment service system",
        "Developed dozens of fully custom themes for Drupal and Wordpress",
        "Designed and developed a custom integration to connect time-tracking with a payroll system",
        "Created several custom modules/plugins for Drupal and Wordpress",
        "Developed custom software to run an interactive game show"
      ],
    }
  },
  computed: {
    sortedTasks() {
      return this.tasks;
    }
  },
  methods: {
    changeSort(type) {
      switch (type) {
        case 'random':
          this.tasks = this.tasks.sort((a,b) => a.length - b.length);
          this.currentSort = 'length';
          break;

        case 'length':
          this.tasks = this.shuffle(this.tasks);
          this.currentSort = 'random';
          break;
      
        default:
          break;
      }
    },
    shuffle(a) {
      for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
      }
      return a;
    }
  }
}
</script>

<style>

</style>
