// components/Stats.vue
<template>
  <div class="container relative pt-0 md:pt-36">

    <h2 class="max-w-lg mx-auto text-center mb-14 heading-2 dark:text-white">With the experience to back it up.</h2>

<div class="absolute -left-20 top-36 md:-top-64 code-block">
const stats = [
<template v-for="stat, index in stats"><pre :key="index">
  {
    value: <code-input :color="stat.color" :initial-value="stat.value" :name="stat.label" @update="updateStat($event, index)" />,
    label: {{ stat.label }}
  }<span v-if="index < stats.length - 1">,</span>
</pre></template>
]
</div>

<pre class="absolute top-0 -right-12 sm:right-0 code-block" aria-hidden="true">
{
  value: Number,
  label: String
}
</pre>

    <div class="relative z-10 max-w-screen-lg mx-auto">
      <ul v-if="stats" class="flex flex-col items-center justify-center space-y-16 md:flex-row md:space-y-0 md:space-x-12 lg:space-x-24">
        <li v-for="stat, index in stats" :key="index">
          <stat :stat="stat" />
        </li>
      </ul>
      <p class="mt-8 ml-8 code-block" aria-hidden="true">for stat in stats</p>
    </div>
    
  </div>
</template>

<script>
export default {
  data() {
    return {
      stats: [
        {
          value: new Date().getFullYear() - 2015,
          label: "Years of Experience",
          color: 'text-lightula-green dark:text-darkula-green',
          suffix: ''
        },
        {
          value: 50,
          label: "Websites",
          color: 'text-lightula-yellow dark:text-darkula-yellow',
          suffix: '+'
        },
        {
          value: 5,
          label: "Web apps",
          color: 'text-lightula-pink dark:text-darkula-pink',
          suffix: '+'
        },
      ]
    }
  },
  methods: {
    updateStat(value, index) {
      console.log(value, index);
      this.stats[index].value = value ? value : 0;
    }
  }
}
</script>

<style>

</style>

// src/components/Stats.tsx
type Props = {};

const Stats = (props: Props) => {
  const stats = [
    {
      title: '8+',
      description: 'Years of Experience',
    },
    {
      title: '70+',
      description: 'Websites',
    },
    {
      title: '10+',
      description: 'Webapps',
    },
  ];

  return (
    <section className='wrapper'>
      <div className='bg-theme rounded-2xl text-theme-dark min-h-[80dvh] flex items-center py-[3rem] md:py-[5rem] lg:py-[10.25rem] px-4 lg:px-10'>
        <div className='container grid gap-10'>
          <p className='text-code text-theme-dark'>{'let stats = {'}</p>

          <div className='grid gap-16'>
            <h2 className='text-heading-1 max-w-[43.75rem] text-balance'>With the experience to back it up.</h2>

            <dl className='flex flex-col md:flex-row justify-between gap-8'>
              {stats.map((stat, index) => (
                <div key={index} className='grid gap-4 lg:gap-6'>
                  <dt className='font-code text-[6rem]/[100%] xl:text-[11.25rem]/[100%]'>{stat.title}</dt>
                  <dd className='font-code text-[1rem] xl:text-[1.5rem] tracking-[0.05rem] xl:tracking-[0.075rem] uppercase'>{stat.description}</dd>
                </div>
              ))}
            </dl>
          </div>

          <p className='text-code text-theme-dark'>{'}'}</p>
        </div>
      </div>
    </section>
  );
};

export default Stats;
